from django import forms 

class LogForm(forms.Form):
	bin = forms.CharField(max_length = 50)
	Geomery_verify_ratio = forms.CharField(max_length = 50)
	Max_images_from_geomery_verify= forms.CharField(max_length = 50)
	Use_model_focal_length= forms.CharField(max_length = 50)
	Feature_extraction_device_index= forms.CharField(max_length = 50)
	Perf_test= forms.CharField(max_length = 50)
	Index_type= forms.CharField(max_length = 50)
	Max_num_images= forms.CharField(max_length = 50)
	Abs_pose_min_num_inliers= forms.CharField(max_length = 50)
	Min_focal_length_ratio= forms.CharField(max_length = 50)
	Max_focal_length_ratio= forms.CharField(max_length = 50)
	Max_matching_distance= forms.CharField(max_length = 50)
	Max_localization_distance_against_gps= forms.CharField(max_length = 50)
	Max_image_size= forms.CharField(max_length = 50)
	Max_num_features= forms.CharField(max_length = 50)
	Gps_filter= forms.CharField(max_length = 50)
	Faiss_knn_num= forms.CharField(max_length = 50)
	Min_co_visible_matches_num= forms.CharField(max_length = 50)
	Geo_verify_type= forms.CharField(max_length = 50)
	Verify_score_threshold= forms.CharField(max_length = 50)
	Temp_gpu_memory= forms.CharField(max_length = 50)
	Use_opt_siftgpu= forms.CharField(max_length = 50)
	Convert2grey_gpu= forms.CharField(max_length = 50)
	DoPopulate= forms.CharField(max_length = 50)
	Faiss_gpu_device_index= forms.CharField(max_length = 50)
	Index_path= forms.CharField(max_length = 50)
	Model_path= forms.CharField(max_length = 50)
	Perf_test_images= forms.CharField(max_length = 50)
	Database_path= forms.CharField(max_length = 50)
	User= forms.CharField(max_length = 50)
	Testname= forms.CharField(max_length = 50)
	